version: '3'

services:
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    command: dockerize -template /etc/nginx/conf.d/nginx.tmpl:/etc/nginx/conf.d/default.conf -stdout /var/log/nginx/access.log -stderr /var/log/nginx/error.log -wait tcp://app:9000 nginx -g 'daemon off;'
    volumes:
      - .:/var/www
    environment:
      - PHP_FPM_HOST=app
      - PHP_FPM_PORT=9000
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - app

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/app/entrypoint.sh
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
